### PR TITLE
Fix same commandline short code being used twice for different options

### PR DESCRIPTION
**Pull request by topcheese13**

### CODE REVIEW

**Comment by DaazKu** [comment]
You could also not provide a short option instead of putting "b" for table.
What do you think?

**Comment by topcheese13** [comment]
That's actually the first thing I did, but I wasn't sure having an option with no shortcode was acceptable in `commandline-functions`.

**Comment by DaazKu** [comment]
I think is it: https://github.com/vanilla/porter/pull/156/files#diff-b71e4609ae160c2275818972cabf5c37R141

**Comment by topcheese13** [comment]
I was referring more to "standard" wise but fair enough, short code completely removed for tables.

**Pull request merged**
