### PR TITLE
Add a new option to allow empty prefixes

### PR DESCRIPTION
**Pull request by Daazku**
It seems that if you write 'porter.php --prefix=""' the get_opts function will treat this as if you did not provide the prefix option. This is a source of problem because we want to be able to set empty prefixes sometime.
The new option --emptyprefix was added to resolve the issue.

### CODE REVIEW

**Comment by linc** [comment]
What does omitting the `prefix` parameter currently do? Use the package default or make it blank?

**Comment by Daazku** [comment]
Since PR #89,
not supplying a prefix is supposed to use the package default but there is currently a problem...
 
When an option is not supplied we define it as its default value. 
This means that prefix is always set no matter what.

I tried to just set its default value to "PACKAGE_DEFAULT", so that we can know we need to use the default package, but we have another problem with that..... 

Using ``porter.php --prefix=""`` is the same as using ``porter.php`` because get_opts treat ``--prefix=""`` as not set so it won't register the option in the returned array.

**Comment by initvector** [comment]
I think we're adding a workaround for an issue that should be addressed.  `getopt` isn't behaving like we expect it to (accepting an option with an empty string as the value).  It might be possible that we need to accept empty strings for future Porter or package options.  Instead of adding a new option to compensate for each case, we could look at revising how we handle command line options.  Garden CLI processes `$argv` to [determine options](https://github.com/vanilla/garden-cli/blob/master/src/Cli.php#L379).  Since `$argv` still retains empty string option values, we might be able to do the same here.

**Comment by Daazku** [comment]
I did not want to parse $argv only for the prefix option and I didn't want to spend to much time on this issue either.
That being said, I think it would be a good idea to write something "à la Garden CLI" that would behave like we wants.

**Pull request merged**
