### PR TITLE
Import all valid contenttype as Discussion.

### PR DESCRIPTION
**Pull request by DaazKu**
As mentioned in #101 there are other contenttype that could be imported as Discussion.

### CODE REVIEW

**Comment by Daazku** [comment]
It seems that the types Link, Gallery, Video have additional data associated with them. Need to figure out it make sense to restore them without the associated data.

* Link -> table( link )
* Gallery -> type( photo ) -> table( photo )
* Video -> table( video )

**Comment by DaazKu** [comment]
On hold until next release

**Comment by linc** [comment]
Then... do a release?

**Comment by DaazKu** [comment]
I wanted to fix more issues but I think I will do a release as is.

**Comment by DaazKu** [comment]
After a bit more investigation I found out that it would not make sense to restore these node type without their additional content. (I also do not have a backup with a whole lot of them so implementing something to restore them properly might be tricky.)

I am gonna close this issue and we can revisit it later if we have a demand for it.

**Pull request closed without merging**
