### PR TITLE
Update esoTalk package

### PR DESCRIPTION
**Pull request by fbjerggaard**
- Fixes the problem I mentioned in #47 in regards to not getting replies to a thread
- Fixes some missing operands for prefix too.

### CODE REVIEW

**Comment by linc** [comment]
Thanks! Can you sign our Contributors Agreement? http://vanillaforums.org/contributors

**Comment by fbjerggaard** [comment]
@linc - Done!

**Comment by linc** [comment]
Thanks!

**Comment by initvector** [comment]
Thanks for this @fbjerggaard!

Just a couple minor things I'd like to see changed and I'll get you merged in:
* Use lowercase for MySQL keywords and reserved words
* Knock the trailing semicolon off the end of the query at [esotalk.php:132](https://github.com/fbjerggaard/porter/blob/master/packages/esotalk.php#L132)

**Comment by fbjerggaard** [comment]
@initvector - Should be done now!

**Comment by initvector** [comment]
Excellent!  Thanks again!

**Comment by fbjerggaard** [comment]
No problem! We are also working on improving this even more, put i'll put that in a separate PR if we ever get it to work :)

**Comment by jamesn81** [comment]
Hi Guys,

I'm not really a coder or contributor to much on git, but I did try to use this esotalk > vanilla converter.

When changing uppercase to lowercase stuff, one of the '**order by**' lines was changed to '**group by**' on the last line below.

It failed until I changed this and now it works for me - not sure how to commit/etc as I'm just a baby, but here it is :)

`// The body of the OP is in the post table.
        $ex->exportTable('Discussion', "
                        select
                                c.conversationId,
                                c.title,
                                c.channelId,
                                p.memberId,
                                c.sticky,
                                c.locked,
                                c.lastPostMemberId,
                                p.content,
                                'BBCode' as Format,
                                from_unixtime(startTime) as DateInserted,
                                from_unixtime(lastPostTime) as DateLastComment
                        from :_conversation c
                        left join :_post p
                                on p.conversationId = c.conversationId
                        where private = 0
                        group by c.conversationId
                        order by p.time", $discussion_Map);`

Thanks so much for writing it - esotalk is super random as a forum and not supported anymore.

I just had success running it tonight with the latest dev version of esotalk.

screen shot 2016-09-02 at 8 24 58 pm

**Pull request merged**
