### PR TITLE
Support for CodoForum 3

### PR DESCRIPTION
**Pull request by HansAdema**
A package to export data from CodoForum. Simple but effective. Tested with CodoForum 3.7.2, but should work with any version of CodoForum 3.

### CODE REVIEW

**Comment by linc** [comment]
Howdy @HansAdema, can you manually say you agree to the CLA here? https://gist.github.com/tburry/9647083c91a9b077381af7af8fac3836

I've hooked it up to automate the process in the future now.

**Comment by HansAdema** [comment]
I have read and agree to the CLA.

**Comment by linc** [comment]
Thanks!

**Comment by DaazKu** [comment]
I took the liberty of updating the code formatting.
Could you update your PR. I'll merge afterward

```php
<?php
/**
 * Codoforum exporter tool. Tested with CodoForum v3.7.
 *
 * @copyright 2009-2017 Vanilla Forums Inc.
 * @license http://opensource.org/licenses/gpl-2.0.php GNU GPL2
 * @author HansAdema
 * @package VanillaPorter
 */

$supported['codoforum'] = array(
    'name'=> 'CodoForum',
    'prefix' => 'codo_',
    'features' => array(
        'Comments' => 1,
        'Discussions' => 1,
        'Users' => 1,
        'Categories' => 1,
        'Roles' => 1,
        'Passwords' => 1,
        'Avatars' => 0,
        'PrivateMessages' => 0,
        'Signatures' => 1,
        'Attachments' => 0,
        'Bookmarks' => 0,
        'Permissions' => 0,
        'UserNotes' => 0,
    ),
);

class Codoforum extends ExportController {
    /** @var array Required tables => columns */
    protected $sourceTables = array(
        'users' => array('id', 'username', 'mail', 'user_status', 'pass', 'signature'),
        'roles' => array('rid', 'rname'),
        'user_roles' => array('uid', 'rid'),
        'categories' => array('cat_id', 'cat_name'),
        'topics' => array('topic_id', 'cat_id', 'uid', 'title'),
        'posts' => array('post_id', 'topic_id', 'uid', 'imessage'),
    );

    /**
     * Main export process.
     *
     * @param ExportModel $ex
     * @see $_structures in ExportModel for allowed destination tables & columns.
     */
    public function forumExport($ex) {

        $characterSet = $ex->getCharacterSet('codo_posts');
        if ($characterSet) {
            $ex->characterSet = $characterSet;
        }

        $ex->beginExport('', 'CodoForum');

        // User.
        $ex->exportTable('User', "
            select 
                u.id as UserID, 
                u.username as Name, 
                u.mail as Email, 
                u.user_status as Verified, 
                u.pass as Password, 
                'Vanilla' as HashMethod,
                from_unixtime(u.created) as DateFirstVisit
            from :_users u
         ");

        // Role.
        $ex->exportTable('Role', "
            select 
                r.rid as RolesID,
                r.rname as Name
            from :_roles r
        ");

        // User Role.
        $ex->exportTable('UserRole', "
            select 
                ur.uid as UserID,
                ur.rid as RoleID
            from :_user_roles ur
            where ur.is_primary = 1
        ");
        
        // UserMeta.
        $ex->exportTable('UserMeta', "
            select
                u.id as UserID,
                'Plugin.Signatures.Sig' as Name,
                u.signature as Value
            from :_users u
            where u.signature != '' and u.signature is not null"
        );
        
        // Category.
        $ex->exportTable('Category', "
            select 
                c.cat_id as CategoryID,
                c.cat_name as Name
            from :_categories c
        ");

        // Discussion.
        $ex->exportTable('Discussion', "
            select
                t.topic_id as DiscussionID,
                t.cat_id as CategoryID,
                t.uid as InsertUserID,
                t.title as Name,
                from_unixtime(t.topic_created) as DateInserted,
                from_unixtime(t.last_post_time) as DateLastComment
            from :_topics t
        ");
        
        // Comment.
        $ex->exportTable('Comment', "
            select
                p.post_id as CommentID,
                p.topic_id as DiscussionID,
                p.uid as InsertUserID,
                p.imessage as Body,
                'Markdown' as Format,
                from_unixtime(p.post_created) as DateInserted
            from :_posts p
        ");

        // TODO UserDiscussion.
        // This is the table for assigning bookmarks/subscribed threads.

        // TODO Media.
        // Attachment data goes here. Vanilla attachments are files under the /uploads folder.
        // This is usually the trickiest step because you need to translate file paths.
        // If you need to export blobs from the database, see the vBulletin porter.

        // TODO Conversations.
        // Private messages often involve the most data manipulation.
        // If you need a large number of complex SQL statements, consider making it a separate method
        // to keep the main process easy to understand. Pass $ex as a parameter if you do.

        $ex->endExport();
    }
}

// Closing PHP tag required. (make.php)
?>
```

**Comment by DaazKu** [comment]
Thank you!

**Comment by HansAdema** [comment]
@DaazKu No problem, I have applied your code style now (I think). Please let me know if there's anything else I need to do.

**Pull request merged**
